### ISSUE TITLE
require returns Array then errors followed by permit

### ISSUE THREAD

**Issue by leckylao** [rails/strong_parameters#140]
From Readme:

> To whitelist an entire hash of parameters, the permit! method can be used
> 
> params.require(:log_entry).permit!

In my console:

``` ruby
irb(main):039:0> raw_parameters = { :teams => ["37"] }
=> {:teams=>["37"]}
irb(main):040:0> parameters = ActionController::Parameters.new(raw_parameters)
=> {"teams"=>["37"]}
irb(main):045:0> parameters.require(:teams).permit!
NoMethodError: undefined method `permit!' for ["37"]:Array
    from (irb):45
    from /home/leckylao/.rbenv/versions/2.0.0-rc2/lib/ruby/gems/2.0.0/gems/railties-4.0.0.rc1/lib/rails/commands/console.rb:90:in `start'
    from /home/leckylao/.rbenv/versions/2.0.0-rc2/lib/ruby/gems/2.0.0/gems/railties-4.0.0.rc1/lib/rails/commands/console.rb:9:in `start'
    from /home/leckylao/.rbenv/versions/2.0.0-rc2/lib/ruby/gems/2.0.0/gems/railties-4.0.0.rc1/lib/rails/commands.rb:66:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

Looks like the Readme needs to update with the correct API

**Comment by NikoRoberts** [comment]
@guy-silva and I ran into this dealing with Mandrill inbound webhooks
Hopefully this helps some people 

```ruby
params = ActionController::Parameters.new({
  mandrill_events: [
    {
      msg: {
          name: 'Francesco',
          age:  22,
          role: 'admin'
        }
    },
    {
      msg: {
        name: 'steve',
        age:  22,
        role: 'admin'
      }
    }
  ]
})
permitted = params.require(:mandrill_events).map { |m| m.require(:msg).permit(:name, :age) }
# => [{"name"=>"Francesco", "age"=>22}, {"name"=>"steve", "age"=>22}] 
```

**Comment by ryankc33** [comment]
@vdmgolub 
You're a lifesaver!

**Comment by ryanmtaylor** [comment]
It's honestly so much easier to do
```
params.require :photos
params.permit photos: [:title, :src]
```
and just not chain them.

**Comment by kirantpatil** [comment]
@ryanmtaylor  I am getting ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError).

Error log:
----------
ActiveModel::ForbiddenAttributesError (ActiveModel::ForbiddenAttributesError):
  
app/controllers/traumas_controller.rb:28:in `block in create_multiple'
app/controllers/traumas_controller.rb:27:in `each'
app/controllers/traumas_controller.rb:27:in `create_multiple'


I did as per your suggestion as below.

stdout output:
-----------------
Started POST "/traumas/create_multiple" for 127.0.0.1 at 2016-10-05 14:38:49 +0530
Processing by TraumasController#create_multiple as JS
  Parameters: {"utf8"=>"✓", "fields"=>[{"contusions"=>"1", "burns"=>"", "at_scene"=>"At Scene", "emergency_detail_id"=>"97", "trauma_region"=>"Head-Back"}], "commit"=>"Submit"}
  User Load (1.6ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 3], ["LIMIT", 1]]
Unpermitted parameters: utf8, commit
[<ActionController::Parameters {"contusions"=>"1", "burns"=>"", "at_scene"=>"At Scene", "emergency_detail_id"=>"97", "trauma_region"=>"Head-Back"} permitted: false>]
Completed 500 Internal Server Error in 6ms (ActiveRecord: 1.6ms)

Controller method:
-----------------------
```
def create_multiple
    trauma_params
    puts params[:fields].inspect
    params[:fields].each do |values|
       u = Trauma.create(values)
    end
  end
```

 ```
   def trauma_params
      params.require :fields
   params.permit fields: [:fractures, :abrasions, :contusions, :laceration , :bleeding_controlled, :bleeding_uncontrolled ,:burns, :at_scene, :emergency_detail_id, :trauma_region]
    end
```

**Comment by kirantpatil** [comment]
Resolved by referring @vdmgolub  code.
